# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{connie}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Leandro Pedroni"]
  s.date = %q{2011-04-11}
  s.description = %q{Heavily based on Forgery it uses the same word sources. It's built to be a bit more customisable and allows you to define new strategies and styles both using ruby modules or big text lists.}
  s.email = %q{ilpoldo@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "connie.gemspec",
    "lib/connie.rb",
    "lib/connie/connie.rb",
    "lib/connie/dictionary.rb",
    "lib/connie/generators.rb",
    "lib/connie/generators/dictionary.rb",
    "lib/connie/parser.rb",
    "lib/dictionaries/creative.rb",
    "lib/dictionaries/creative/color",
    "lib/dictionaries/creative/lorem_ipsum_lines",
    "lib/dictionaries/geo.rb",
    "lib/dictionaries/geo/city",
    "lib/dictionaries/geo/country",
    "lib/dictionaries/geo/language",
    "lib/dictionaries/geo/province",
    "lib/dictionaries/geo/province_short",
    "lib/dictionaries/geo/race",
    "lib/dictionaries/geo/state",
    "lib/dictionaries/geo/state_short",
    "lib/dictionaries/geo/street",
    "lib/dictionaries/geo/street_suffix",
    "lib/dictionaries/language/frequency",
    "lib/dictionaries/names.rb",
    "lib/dictionaries/names/company",
    "lib/dictionaries/names/female",
    "lib/dictionaries/names/female_title",
    "lib/dictionaries/names/last",
    "lib/dictionaries/names/male",
    "lib/dictionaries/names/male_title",
    "lib/dictionaries/names/suffix",
    "lib/dictionaries/net/top_level_domain",
    "lib/dictionaries/numbers.rb",
    "lib/dictionaries/shopping.shirt_size",
    "spec/connie_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_dictionaries/names/male",
    "spec/test_dictionaries/numbers/ordinal"
  ]
  s.homepage = %q{http://github.com/ilpoldo@gmail.com/connie}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Little compact library to synthesise data that does not load big files in memory}
  s.test_files = [
    "spec/connie_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

